const AppError = require("../utils/appError");
const { catchAsync } = require("../Utils/catchAsync");

exports.userRegister = catchAsync(async (req, res, next) => {});
exports.userLogin = catchAsync(async (req, res, next) => {});
exports.userEdit = catchAsync(async (req, res, next) => {});
exports.userResetPassword = catchAsync(async (req, res, next) => {});
exports.userForgetPassword = catchAsync(async (req, res, next) => {});
exports.userCart = catchAsync(async (req, res, next) => {});
exports.userOrders = catchAsync(async (req, res, next) => {});
